[build]
  command = "npm run build"
  publish = "dist"

# Redirect all requests to index.html so client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
